import { relations, sql } from "drizzle-orm";
import { boolean, check, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";

const timestamps = { createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() };

export const clinicRole = pgEnum("clinic_role", ["CLINIC_OWNER", "CLINIC_ADMIN", "RECEPTIONIST", "DENTIST", "DENTAL_ASSISTANT"]);
export const membershipStatus = pgEnum("membership_status", ["INVITED", "ACTIVE", "SUSPENDED"]);
export const appointmentStatus = pgEnum("appointment_status", ["PENDING", "CONFIRMED", "CHECKED_IN", "IN_PROGRESS", "COMPLETED", "CANCELLED", "NO_SHOW", "RESCHEDULED"]);
export const subscriptionStatus = pgEnum("subscription_status", ["TRIALING", "ACTIVE", "PAST_DUE", "CANCELLED"]);
export const notificationStatus = pgEnum("notification_status", ["PENDING", "PROCESSING", "DELIVERED", "FAILED"]);

export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(), name: varchar("name", { length: 160 }).notNull(), email: varchar("email", { length: 320 }).notNull(), emailVerified: boolean("email_verified").notNull().default(false), image: text("image"), platformAdmin: boolean("platform_admin").notNull().default(false), ...timestamps
}, (t) => [uniqueIndex("users_email_unique").on(t.email)]);

export const sessions = pgTable("sessions", { id: text("id").primaryKey(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), token: text("token").notNull(), ipAddress: text("ip_address"), userAgent: text("user_agent"), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), ...timestamps }, (t) => [uniqueIndex("sessions_token_unique").on(t.token), index("sessions_user_idx").on(t.userId)]);
export const accounts = pgTable("accounts", { id: text("id").primaryKey(), accountId: text("account_id").notNull(), providerId: text("provider_id").notNull(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), accessToken: text("access_token"), refreshToken: text("refresh_token"), idToken: text("id_token"), accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }), refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }), scope: text("scope"), password: text("password"), ...timestamps }, (t) => [index("accounts_user_idx").on(t.userId)]);
export const verifications = pgTable("verifications", { id: text("id").primaryKey(), identifier: text("identifier").notNull(), value: text("value").notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), ...timestamps }, (t) => [index("verifications_identifier_idx").on(t.identifier)]);

export const clinics = pgTable("clinics", { id: uuid("id").primaryKey().defaultRandom(), name: varchar("name", { length: 160 }).notNull(), slug: varchar("slug", { length: 160 }).notNull(), active: boolean("active").notNull().default(true), ...timestamps }, (t) => [uniqueIndex("clinics_slug_unique").on(t.slug)]);
export const clinicMembers = pgTable("clinic_members", { id: uuid("id").primaryKey().defaultRandom(), clinicId: uuid("clinic_id").notNull().references(() => clinics.id, { onDelete: "cascade" }), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), role: clinicRole("role").notNull(), status: membershipStatus("status").notNull().default("ACTIVE"), ...timestamps }, (t) => [uniqueIndex("clinic_members_clinic_user_unique").on(t.clinicId, t.userId), index("clinic_members_user_idx").on(t.userId)]);
export const clinicLocations = pgTable("clinic_locations", { id: uuid("id").primaryKey().defaultRandom(), clinicId: uuid("clinic_id").notNull().references(() => clinics.id, { onDelete: "cascade" }), name: varchar("name", { length: 160 }).notNull(), timezone: varchar("timezone", { length: 80 }).notNull(), addressLine1: varchar("address_line_1", { length: 200 }).notNull(), city: varchar("city", { length: 120 }).notNull(), active: boolean("active").notNull().default(true), ...timestamps }, (t) => [index("clinic_locations_tenant_idx").on(t.clinicId)]);
export const clinicSettings = pgTable("clinic_settings", { clinicId: uuid("clinic_id").primaryKey().references(() => clinics.id, { onDelete: "cascade" }), slotIntervalMinutes: integer("slot_interval_minutes").notNull().default(15), reminderHours: integer("reminder_hours").notNull().default(24), bookingEnabled: boolean("booking_enabled").notNull().default(false), ...timestamps }, (t) => [check("clinic_settings_slot_interval_check", sql`${t.slotIntervalMinutes} between 5 and 120`)]);
export const clinicInvitations = pgTable("clinic_invitations", { id: uuid("id").primaryKey().defaultRandom(), clinicId: uuid("clinic_id").notNull().references(() => clinics.id, { onDelete: "cascade" }), email: varchar("email", { length: 320 }).notNull(), role: clinicRole("role").notNull(), tokenHash: text("token_hash").notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), acceptedAt: timestamp("accepted_at", { withTimezone: true }), invitedBy: uuid("invited_by").notNull().references(() => users.id), ...timestamps }, (t) => [index("clinic_invitations_tenant_idx").on(t.clinicId)]);

export const dentists = pgTable("dentists", { id: uuid("id").primaryKey().defaultRandom(), clinicId: uuid("clinic_id").notNull().references(() => clinics.id, { onDelete: "cascade" }), userId: uuid("user_id").references(() => users.id), displayName: varchar("display_name", { length: 160 }).notNull(), bio: text("bio"), active: boolean("active").notNull().default(true), ...timestamps }, (t) => [index("dentists_tenant_idx").on(t.clinicId)]);
export const dentistLocationAssignments = pgTable("dentist_location_assignments", { id: uuid("id").primaryKey().defaultRandom(), clinicId: uuid("clinic_id").notNull().references(() => clinics.id, { onDelete: "cascade" }), dentistId: uuid("dentist_id").notNull().references(() => dentists.id, { onDelete: "cascade" }), locationId: uuid("location_id").notNull().references(() => clinicLocations.id, { onDelete: "cascade" }), ...timestamps }, (t) => [uniqueIndex("dentist_location_unique").on(t.dentistId, t.locationId), index("dentist_location_tenant_idx").on(t.clinicId)]);
export const services = pgTable("services", { id: uuid("id").primaryKey().defaultRandom(), clinicId: uuid("clinic_id").notNull().references(() => clinics.id, { onDelete: "cascade" }), name: varchar("name", { length: 160 }).notNull(), durationMinutes: integer("duration_minutes").notNull(), priceCents: integer("price_cents").notNull().default(0), active: boolean("active").notNull().default(true), ...timestamps }, (t) => [index("services_tenant_idx").on(t.clinicId), check("services_duration_check", sql`${t.durationMinutes} between 5 and 480`)]);
export const dentistServices = pgTable("dentist_services", { clinicId: uuid("clinic_id").notNull().references(() => clinics.id, { onDelete: "cascade" }), dentistId: uuid("dentist_id").notNull().references(() => dentists.id, { onDelete: "cascade" }), serviceId: uuid("service_id").notNull().references(() => services.id, { onDelete: "cascade" }) }, (t) => [uniqueIndex("dentist_service_unique").on(t.dentistId, t.serviceId), index("dentist_service_tenant_idx").on(t.clinicId)]);
export const dentistSchedules = pgTable("dentist_schedules", { id: uuid("id").primaryKey().defaultRandom(), clinicId: uuid("clinic_id").notNull().references(() => clinics.id, { onDelete: "cascade" }), dentistId: uuid("dentist_id").notNull().references(() => dentists.id, { onDelete: "cascade" }), locationId: uuid("location_id").notNull().references(() => clinicLocations.id, { onDelete: "cascade" }), weekday: integer("weekday").notNull(), startMinute: integer("start_minute").notNull(), endMinute: integer("end_minute").notNull(), active: boolean("active").notNull().default(true), ...timestamps }, (t) => [index("dentist_schedules_tenant_idx").on(t.clinicId), check("dentist_schedule_time_check", sql`${t.weekday} between 0 and 6 and ${t.startMinute} >= 0 and ${t.endMinute} <= 1440 and ${t.startMinute} < ${t.endMinute}`)]);
export const dentistScheduleExceptions = pgTable("dentist_schedule_exceptions", { id: uuid("id").primaryKey().defaultRandom(), clinicId: uuid("clinic_id").notNull().references(() => clinics.id, { onDelete: "cascade" }), dentistId: uuid("dentist_id").notNull().references(() => dentists.id, { onDelete: "cascade" }), locationId: uuid("location_id").references(() => clinicLocations.id), startsAt: timestamp("starts_at", { withTimezone: true }).notNull(), endsAt: timestamp("ends_at", { withTimezone: true }).notNull(), available: boolean("available").notNull().default(false), ...timestamps }, (t) => [index("dentist_schedule_exceptions_tenant_idx").on(t.clinicId)]);
export const dentistTimeOff = pgTable("dentist_time_off", { id: uuid("id").primaryKey().defaultRandom(), clinicId: uuid("clinic_id").notNull().references(() => clinics.id, { onDelete: "cascade" }), dentistId: uuid("dentist_id").notNull().references(() => dentists.id, { onDelete: "cascade" }), startsAt: timestamp("starts_at", { withTimezone: true }).notNull(), endsAt: timestamp("ends_at", { withTimezone: true }).notNull(), reason: text("reason"), ...timestamps }, (t) => [index("dentist_time_off_tenant_idx").on(t.clinicId)]);

export const patientProfiles = pgTable("patient_profiles", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").references(() => users.id), firstName: varchar("first_name", { length: 80 }).notNull(), lastName: varchar("last_name", { length: 80 }).notNull(), email: varchar("email", { length: 320 }).notNull(), phone: varchar("phone", { length: 30 }).notNull(), ...timestamps }, (t) => [index("patient_profiles_email_idx").on(t.email)]);
export const clinicPatients = pgTable("clinic_patients", { id: uuid("id").primaryKey().defaultRandom(), clinicId: uuid("clinic_id").notNull().references(() => clinics.id, { onDelete: "cascade" }), patientProfileId: uuid("patient_profile_id").notNull().references(() => patientProfiles.id), archived: boolean("archived").notNull().default(false), ...timestamps }, (t) => [uniqueIndex("clinic_patient_unique").on(t.clinicId, t.patientProfileId), index("clinic_patients_tenant_idx").on(t.clinicId)]);
export const appointments = pgTable("appointments", { id: uuid("id").primaryKey().defaultRandom(), clinicId: uuid("clinic_id").notNull().references(() => clinics.id, { onDelete: "cascade" }), locationId: uuid("location_id").notNull().references(() => clinicLocations.id), dentistId: uuid("dentist_id").notNull().references(() => dentists.id), clinicPatientId: uuid("clinic_patient_id").notNull().references(() => clinicPatients.id), serviceId: uuid("service_id").notNull().references(() => services.id), startsAt: timestamp("starts_at", { withTimezone: true }).notNull(), endsAt: timestamp("ends_at", { withTimezone: true }).notNull(), status: appointmentStatus("status").notNull().default("PENDING"), notes: text("notes"), ...timestamps }, (t) => [index("appointments_tenant_start_idx").on(t.clinicId, t.startsAt), index("appointments_dentist_start_idx").on(t.dentistId, t.startsAt), check("appointments_range_check", sql`${t.startsAt} < ${t.endsAt}`)]);
export const appointmentStatusHistory = pgTable("appointment_status_history", { id: uuid("id").primaryKey().defaultRandom(), clinicId: uuid("clinic_id").notNull().references(() => clinics.id, { onDelete: "cascade" }), appointmentId: uuid("appointment_id").notNull().references(() => appointments.id, { onDelete: "cascade" }), fromStatus: appointmentStatus("from_status"), toStatus: appointmentStatus("to_status").notNull(), changedBy: uuid("changed_by").references(() => users.id), reason: text("reason"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [index("appointment_history_tenant_idx").on(t.clinicId, t.appointmentId)]);

export const subscriptions = pgTable("subscriptions", { id: uuid("id").primaryKey().defaultRandom(), clinicId: uuid("clinic_id").notNull().references(() => clinics.id, { onDelete: "cascade" }), planCode: varchar("plan_code", { length: 40 }).notNull().default("MVP"), status: subscriptionStatus("status").notNull().default("ACTIVE"), currentPeriodEnd: timestamp("current_period_end", { withTimezone: true }), ...timestamps }, (t) => [uniqueIndex("subscriptions_clinic_unique").on(t.clinicId)]);
export const notificationJobs = pgTable("notification_jobs", { id: uuid("id").primaryKey().defaultRandom(), clinicId: uuid("clinic_id").notNull().references(() => clinics.id, { onDelete: "cascade" }), appointmentId: uuid("appointment_id").references(() => appointments.id, { onDelete: "cascade" }), kind: varchar("kind", { length: 80 }).notNull(), recipient: varchar("recipient", { length: 320 }).notNull(), payload: jsonb("payload").notNull(), idempotencyKey: varchar("idempotency_key", { length: 160 }).notNull(), status: notificationStatus("status").notNull().default("PENDING"), scheduledAt: timestamp("scheduled_at", { withTimezone: true }).notNull(), attempts: integer("attempts").notNull().default(0), lastError: text("last_error"), ...timestamps }, (t) => [uniqueIndex("notification_jobs_idempotency_unique").on(t.idempotencyKey), index("notification_jobs_due_idx").on(t.status, t.scheduledAt)]);
export const notificationDeliveries = pgTable("notification_deliveries", { id: uuid("id").primaryKey().defaultRandom(), clinicId: uuid("clinic_id").notNull().references(() => clinics.id, { onDelete: "cascade" }), jobId: uuid("job_id").notNull().references(() => notificationJobs.id, { onDelete: "cascade" }), provider: varchar("provider", { length: 40 }).notNull(), providerMessageId: text("provider_message_id"), deliveredAt: timestamp("delivered_at", { withTimezone: true }), errorCode: text("error_code"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const fileObjects = pgTable("file_objects", { id: uuid("id").primaryKey().defaultRandom(), clinicId: uuid("clinic_id").notNull().references(() => clinics.id, { onDelete: "cascade" }), ownerType: varchar("owner_type", { length: 60 }).notNull(), ownerId: uuid("owner_id").notNull(), storageProvider: varchar("storage_provider", { length: 30 }).notNull().default("R2"), bucket: text("bucket").notNull(), objectKey: text("object_key").notNull(), mimeType: varchar("mime_type", { length: 160 }).notNull(), sizeBytes: integer("size_bytes").notNull(), createdBy: uuid("created_by").notNull().references(() => users.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("file_objects_key_unique").on(t.objectKey), index("file_objects_tenant_owner_idx").on(t.clinicId, t.ownerId)]);
export const auditLogs = pgTable("audit_logs", { id: uuid("id").primaryKey().defaultRandom(), clinicId: uuid("clinic_id").references(() => clinics.id), actorUserId: uuid("actor_user_id").references(() => users.id), action: varchar("action", { length: 100 }).notNull(), resourceType: varchar("resource_type", { length: 80 }).notNull(), resourceId: uuid("resource_id"), metadata: jsonb("metadata").notNull().default({}), ipAddress: text("ip_address"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [index("audit_logs_tenant_created_idx").on(t.clinicId, t.createdAt)]);
export const webhookEvents = pgTable("webhook_events", { id: uuid("id").primaryKey().defaultRandom(), provider: varchar("provider", { length: 60 }).notNull(), externalId: text("external_id").notNull(), eventType: varchar("event_type", { length: 100 }).notNull(), payloadHash: text("payload_hash").notNull(), processedAt: timestamp("processed_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("webhook_events_provider_external_unique").on(t.provider, t.externalId)]);

export const clinicRelations = relations(clinics, ({ many, one }) => ({ members: many(clinicMembers), locations: many(clinicLocations), subscription: one(subscriptions) }));
export const memberRelations = relations(clinicMembers, ({ one }) => ({ clinic: one(clinics, { fields: [clinicMembers.clinicId], references: [clinics.id] }), user: one(users, { fields: [clinicMembers.userId], references: [users.id] }) }));
