import { useMemo, useState, type FormEvent } from "react";

const services = [{ id: "00000000-0000-4000-8000-000000000101", name: "Dental Check-up", duration: 30, price: "$99" }, { id: "00000000-0000-4000-8000-000000000102", name: "Teeth Cleaning", duration: 45, price: "$129" }, { id: "00000000-0000-4000-8000-000000000103", name: "Fillings", duration: 60, price: "$199" }];
const dentists = [{ id: "00000000-0000-4000-8000-000000000201", name: "Dr. Sarah Lee" }, { id: "00000000-0000-4000-8000-000000000202", name: "Dr. Michael Chen" }];
const times = [
  { label: "8:00 AM", startsAt: "2026-09-03T00:00:00.000Z" },
  { label: "8:30 AM", startsAt: "2026-09-03T00:30:00.000Z" },
  { label: "9:00 AM", startsAt: "2026-09-03T01:00:00.000Z" },
  { label: "9:30 AM", startsAt: "2026-09-03T01:30:00.000Z" },
  { label: "10:00 AM", startsAt: "2026-09-03T02:00:00.000Z" },
  { label: "10:30 AM", startsAt: "2026-09-03T02:30:00.000Z" },
  { label: "11:00 AM", startsAt: "2026-09-03T03:00:00.000Z" },
  { label: "11:30 AM", startsAt: "2026-09-03T03:30:00.000Z" },
];

export function BookingFlow({ clinicSlug, apiUrl }: { clinicSlug: string; apiUrl: string }) {
  const [serviceId, setServiceId] = useState(services[0]!.id); const [dentistId, setDentistId] = useState(dentists[0]!.id); const [startsAt, setStartsAt] = useState(times[2]!.startsAt); const [token, setToken] = useState(""); const [code, setCode] = useState(""); const [message, setMessage] = useState("");
  const selectedService = useMemo(() => services.find((service) => service.id === serviceId)!, [serviceId]); const selectedDentist = dentists.find((dentist) => dentist.id === dentistId)!;
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setMessage("Sending a verification code…");
    const routeSlug = typeof window === "undefined" ? clinicSlug : window.location.pathname.split("/").filter(Boolean).at(-1) ?? clinicSlug;
    const resolvedSlug = routeSlug === "book" ? clinicSlug : routeSlug;
    const response = await fetch(`${apiUrl}/api/v1/public/clinics/verify`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ clinicSlug: resolvedSlug, locationId: data.get("locationId"), dentistId, serviceId, startsAt, patient: { firstName: data.get("firstName"), lastName: data.get("lastName"), email: data.get("email"), phone: data.get("phone") } }) }); const result = await response.json() as { data?: { bookingToken: string }; error?: { message: string } }; if (!response.ok || !result.data) { setMessage(result.error?.message ?? "We could not start this booking."); return; } setToken(result.data.bookingToken); setMessage("Enter the six-digit code sent to your email."); }
  async function confirm() { const response = await fetch(`${apiUrl}/api/v1/public/clinics/confirm`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ bookingToken: token, code }) }); const result = await response.json() as { data?: { appointmentId: string }; error?: { message: string } }; setMessage(response.ok ? "Your appointment is confirmed." : result.error?.message ?? "We could not confirm this booking."); }
  const selectedTime = times.find((slot) => slot.startsAt === startsAt)!;
  return <div className="booking-card"><div className="booking-title"><h1>Book an appointment</h1><p>Northstar Dental Studio</p><div className="steps"><span className="active">1 Service</span><span>2 Dentist</span><span>3 Time</span><span>4 Details</span></div></div><div className="booking-grid"><form className="booking-form" onSubmit={submit}><section><h2>1. Choose a location</h2><input type="hidden" name="locationId" value="00000000-0000-4000-8000-000000000001"/><button className="option selected" type="button"><span>Northstar Dental Studio<br/><small>456 Northstar Blvd, Suite 200</small></span><span>Manila</span></button></section><section><h2>2. Select a service</h2><div className="option-grid">{services.map((service) => <button type="button" className={`option ${service.id === serviceId ? "selected" : ""}`} onClick={() => setServiceId(service.id)} key={service.id}><span>{service.name}</span><span>{service.duration} min · {service.price}</span></button>)}</div></section><section><h2>3. Choose a dentist</h2><div className="option-grid">{dentists.map((dentist) => <button type="button" className={`option ${dentist.id === dentistId ? "selected" : ""}`} onClick={() => setDentistId(dentist.id)} key={dentist.id}>{dentist.name}</button>)}</div></section><section><h2>4. Select a time</h2><div className="times">{times.map((slot) => <button type="button" className={`option ${slot.startsAt === startsAt ? "selected" : ""}`} onClick={() => setStartsAt(slot.startsAt)} key={slot.startsAt}>{slot.label}</button>)}</div></section><section><h2>5. Your details</h2><div className="fields"><label className="field">First name<input required name="firstName" autoComplete="given-name"/></label><label className="field">Last name<input required name="lastName" autoComplete="family-name"/></label><label className="field">Email<input required type="email" name="email" autoComplete="email"/></label><label className="field">Phone<input required type="tel" name="phone" autoComplete="tel"/></label></div></section>{message ? <div className="message" role="status">{message}</div> : null}{token ? <div className="fields"><label className="field">Verification code<input value={code} onChange={(event) => setCode(event.target.value)} inputMode="numeric" maxLength={6}/></label><button className="button" type="button" onClick={confirm}>Confirm appointment</button></div> : <button className="button" type="submit">Continue securely</button>}</form><aside className="summary"><h2>Your appointment</h2><dl><div><dt>Location</dt><dd>Northstar Dental Studio</dd></div><div><dt>Service</dt><dd>{selectedService.name} · {selectedService.duration} min</dd></div><div><dt>Dentist</dt><dd>{selectedDentist.name}</dd></div><div><dt>Date</dt><dd>Thursday, September 3</dd></div><div><dt>Time</dt><dd>{selectedTime.label}</dd></div></dl></aside></div></div>;
}
